Exercises for Ch.Syntax & Ch.Elaboration
arthurpaulino/lean4-metaprogramming-book pull request #87
Opened 2023-02-24 08:42 UTC by lakesare

2023-03-08 22:09 UTC, hargoniX requested changes
Just my remarks on the syntax chapter since that's the one I am most familiar with.

Its mostly just didactic nit picks, I think the approach is quite good in general :+1:

2023-03-08 22:09 UTC, hargoniX commented on lean/main/syntax.lean
> +4. Mathlib has a `#help option` command that displays all options available in the current environment, and their descriptions. `#help option pp.r` will display all options starting with a "pp.r" sub
I find the task to be a little ambiguous here, people could think you want them to only  allow identifiers of options which is not possible without an elaborator, maybe make this a little more clear?

2023-03-08 22:09 UTC, hargoniX commented on lean/main/syntax.lean
> +5. Mathlib has a ∑ operator. Create a `syntax` rule that would accept the following terms:
I think you should make it clear here already that you need std4 in order to use these binders (and that it is also possible to do without them)

2023-03-14 01:10 UTC, lakesare commented
@arthurpaulino, I think it's good to merge.

2023-03-14 01:11 UTC, arthurpaulino commented
Amazing, thank you!

2023-03-14 01:12 UTC, merged